add_includedirs("./include/")
add_requires("openmp")
add_requires("gtest")
add_cxxflags("-O3 -ftree-vectorize -fstrict-aliasing -march=native -mtune=native -fopt-info-vec-optimized")

target("DesignMatrix")
  set_kind("shared")
  add_files("./src/DesignMatrix.cpp")
  add_deps("BinSpMV")
  add_packages("openmp")

target("test_DesignMatrix")
  set_kind("binary")
  add_files("./tests/test_DesignMatrix.cpp")
  add_packages("gtest")
  add_deps("DesignMatrix")
  add_deps("BinSpMV")
  add_deps("BatchedDesignMatrix")

target("BatchedDesignMatrix")
  set_kind("shared")
  add_files("./src/BatchedDesignMatrix.cpp")
  add_packages("openmp")

target("test_BatchedDesignMatrix")
  set_kind("binary")
  add_files("./tests/test_BatchedDesignMatrix.cpp")
  add_packages("gtest")
  add_deps("DesignMatrix")
  add_deps("BinSpMV")
  add_deps("BatchedDesignMatrix")

target("BinSpMV")
  set_kind("shared")
  add_files("./src/BinSpMV.cpp")
  add_packages("openmp")

target("test_BinSpMv")
  set_kind("binary")
  add_files("./tests/test_BinSpMV.cpp")
  add_packages("gtest")
  add_deps("BinSpMV")

target("batch_binspmv")
    set_kind("shared")
    add_files("./src/batch_binspmv.cu")
    add_deps("BatchedDesignMatrix")
    add_deps("BinSpMV")
    add_cugencodes("native")

target("test_batch_binspmv")
  set_kind("binary")
  add_files("./tests/test_batch_binspmv.cpp")
  add_packages("gtest")
  add_deps("DesignMatrix")
  add_deps("BatchedDesignMatrix")
  add_deps("BinSpMV")
  add_deps("batch_binspmv")

