add_includedirs("./include/")
add_requires("openmp")
add_requires("gtest")
add_cxxflags("-O3 -ftree-vectorize -fstrict-aliasing -march=native -mtune=native -fopt-info-vec-optimized")

target("DesignMatrix")
  set_kind("shared")
  add_files("./src/DesignMatrix.cu")
  add_deps("BinSpMV")
  add_cugencodes("native")
  add_cuflags("-Xcompiler -fopenmp")
  set_targetdir("./build/lib/")

target("test_DesignMatrix")
  set_kind("binary")
  add_files("./tests/test_DesignMatrix.cpp")
  add_packages("gtest")
  add_deps("DesignMatrix")
  add_deps("BinSpMV")
  add_deps("BatchedDesignMatrix")
  add_deps("batch_binspmv")
  set_targetdir("./build/tests/")

target("BatchedDesignMatrix")
  set_kind("shared")
  add_files("./src/BatchedDesignMatrix.cpp")
  add_packages("openmp")
  set_targetdir("./build/lib/")

target("test_BatchedDesignMatrix")
  set_kind("binary")
  add_files("./tests/test_BatchedDesignMatrix.cpp")
  add_packages("gtest")
  add_deps("DesignMatrix")
  add_deps("BinSpMV")
  add_deps("BatchedDesignMatrix")
  set_targetdir("./build/tests/")

target("BinSpMV")
  set_kind("shared")
  add_files("./src/BinSpMV.cpp")
  add_packages("openmp")
  set_targetdir("./build/lib/")

target("test_BinSpMv")
  set_kind("binary")
  add_files("./tests/test_BinSpMV.cpp")
  add_packages("gtest")
  add_deps("BinSpMV")
  set_targetdir("./build/tests/")

target("batch_binspmv")
    set_kind("shared")
    add_files("./src/batch_binspmv.cu")
    add_deps("BatchedDesignMatrix")
    add_deps("BinSpMV")
    add_cugencodes("native")
    set_targetdir("./build/lib/")

target("test_batch_binspmv")
  set_kind("binary")
  add_files("./tests/test_batch_binspmv.cpp")
  add_packages("gtest")
  add_deps("DesignMatrix")
  add_deps("BatchedDesignMatrix")
  add_deps("BinSpMV")
  add_deps("batch_binspmv")
  set_targetdir("./build/tests/")

target("HAL")
  set_kind("shared")
  add_files("./src/HAL.cpp")
  add_deps("DesignMatrix")
  add_deps("BatchedDesignMatrix")
  add_deps("batch_binspmv")
  add_packages("openmp")
  set_targetdir("./build/lib/")

target("cuHAL")
  set_kind("binary")
  add_files("./src/main.cpp")
  add_deps("HAL")
  add_packages("openmp")
  set_targetdir("./build/")
